name: shakosh
description: shakosh

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  localization: ^2.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  awesome_dialog: ^3.1.0
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.5.0
  firebase_auth: ^4.10.0
  country_code_picker: ^3.0.0
  fast_cached_network_image: ^1.2.0
  flutter_svg: ^2.0.7
  math_expressions: ^2.4.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.3
  animated_snack_bar: ^0.3.1
  shimmer: ^3.0.0
  fluro: ^2.0.5
  number_paginator: ^0.4.0
  universal_html: ^2.2.4
  path_provider: ^2.1.1
  flutter_widget_from_html_core: ^0.14.6
  seo_renderer: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#333333"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/muli/Muli-ExtraLight.ttf
          weight: 200
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 700
