// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2yL0rhl1rWGos5L9tZZkcNAVx4xB9TI',
    appId: '1:47848997917:web:1b0428f303285a1699f2f4',
    messagingSenderId: '47848997917',
    projectId: 'shakosh-60e60',
    authDomain: 'shakosh-60e60.firebaseapp.com',
    storageBucket: 'shakosh-60e60.appspot.com',
    measurementId: 'G-2LZKJKK449',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWc_7h1TWdAsgZjku7-9vKVpFyCZErDp8',
    appId: '1:47848997917:android:bb2be99e4957290499f2f4',
    messagingSenderId: '47848997917',
    projectId: 'shakosh-60e60',
    storageBucket: 'shakosh-60e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MQ7W6qqMcnjBCSlxAjyuDInoavNcuZ8',
    appId: '1:47848997917:ios:999602b29711615599f2f4',
    messagingSenderId: '47848997917',
    projectId: 'shakosh-60e60',
    storageBucket: 'shakosh-60e60.appspot.com',
    iosBundleId: 'com.exabytellc.shakosh',
  );
}
